import { ThemeProvider } from '@/components/theme-provider'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { auth } from '@clerk/nextjs/server'
import { SyncActiveOrganization } from '@/components/sync-active-organization'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { sessionClaims } = auth()
  console.log(sessionClaims)
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: 'hsl(263.4, 70%, 50.4%)',
        },
        elements: {
          navbarMobileMenuRow: {
            background: 'transparent',
          },
        },
      }}
    >
      <SyncActiveOrganization membership={sessionClaims?.membership} />
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
